#use_frameworks!
inhibit_all_warnings!

platform :ios, '8.0'

target 'ATShare_Example' do
  pod 'ATShare', :path => '../'

  pod 'ATToast'
  
  target 'ATShare_Tests' do
    inherit! :search_paths
  end
end
